### ISSUE TITLE
[ CONFIGURE SELECTED COMPONENT MENU ] Implementation of string param type

### ISSUE THREAD

**Issue by mvdnet** [occi-cad/occi-freecad-plugin#5]

**Comment by jmwright** [comment]
@mvdnet Is the string parameter type not working? I implemented it but it hasn't gotten a proper test yet.

**Comment by jmwright** [comment]
I see now that a `text` model was added to the scriptlibrary, and the text param type does not work properly. I'll get that fixed.

**Comment by jmwright** [comment]
This is fixed in commit 010b944f300d663d3ff1fb6e9424a20aba5590ae
